In [1]:
import pandas as pd
import ast

In [2]:
results_df = pd.read_csv('./clean/results_jo.csv')
hosts_df = pd.read_csv('./clean/hosts.csv')
athletes_df = pd.read_csv('./clean/athletes.csv')

In [3]:
# athletes_df[athletes_df['athlete_url'] == "https://olympics.com/en/athletes/michael-phelps-ii"]

In [4]:
results_df.loc[(results_df.duplicated())]
results_df = results_df.rename({'slug_game':'game_slug'},axis=1)
results_df.columns

Index(['discipline_title', 'event_title', 'game_slug', 'participant_type',
       'medal_type', 'athletes', 'rank_equal', 'rank_position', 'country_name',
       'country_code', 'country_3_letter_code', 'value_unit', 'value_type',
       'event_gender'],
      dtype='object')

In [5]:
jo_types = hosts_df[['game_slug','game_season', 'game_year']]
hosts_results_merge = results_df.merge(jo_types, on='game_slug')
hosts_results_merge.head()

,discipline_title,event_title,game_slug,participant_type,medal_type,athletes,rank_equal,rank_position,country_name,country_code,country_3_letter_code,value_unit,value_type,event_gender,game_season,game_year
0,Curling,Mixed Doubles,beijing-2022,GameTeam,GOLD,"[('Stefania CONSTANTINI', 'https://olympics.co...",False,1,Italy,IT,ITA,NaN,NaN,Mixed,Winter,2022
1,Curling,Mixed Doubles,beijing-2022,GameTeam,SILVER,"[('Kristin SKASLIEN', 'https://olympics.com/en...",False,2,Norway,NO,NOR,NaN,NaN,Mixed,Winter,2022
2,Curling,Mixed Doubles,beijing-2022,GameTeam,BRONZE,"[('Almida DE VAL', 'https://olympics.com/en/at...",False,3,Sweden,SE,SWE,NaN,NaN,Mixed,Winter,2022
3,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,"[('Jennifer DODDS', 'https://olympics.com/en/a...",False,4,Great Britain,GB,GBR,NaN,NaN,Mixed,Winter,2022
4,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,"[('Rachel HOMAN', 'https://olympics.com/en/ath...",False,5,Canada,CA,CAN,NaN,NaN,Mixed,Winter,2022

In [6]:
summer_games_results = hosts_results_merge.loc[(hosts_results_merge.game_season == 'Summer')].copy()
winter_games_results = hosts_results_merge.loc[(hosts_results_merge.game_season == 'Winter')].copy()
summer_games_results.head()

,discipline_title,event_title,game_slug,participant_type,medal_type,athletes,rank_equal,rank_position,country_name,country_code,country_3_letter_code,value_unit,value_type,event_gender,game_season,game_year
3784,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,GOLD,"[('Fatima GALVEZ', 'https://olympics.com/en/at...",False,1,Spain,ES,ESP,NaN,NaN,Mixed,Summer,2020
3785,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,SILVER,"[('Alessandra PERILLI', 'https://olympics.com/...",False,2,San Marino,SM,SMR,NaN,NaN,Mixed,Summer,2020
3786,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,BRONZE,"[('Madelynn Ann BERNAU', 'https://olympics.com...",False,3,United States of America,US,USA,NaN,NaN,Mixed,Summer,2020
3787,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,NaN,"[('Zuzana STEFECEKOVA', 'https://olympics.com/...",False,4,Slovakia,SK,SVK,NaN,NaN,Mixed,Summer,2020
3788,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,NaN,"[('Yukie NAKAYAMA', 'https://olympics.com/en/a...",False,5,Japan,JP,JPN,NaN,NaN,Mixed,Summer,2020

In [7]:
summer_games_results.drop(['game_season'], axis=1, inplace=True)
summer_games_results.head()

,discipline_title,event_title,game_slug,participant_type,medal_type,athletes,rank_equal,rank_position,country_name,country_code,country_3_letter_code,value_unit,value_type,event_gender,game_year
3784,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,GOLD,"[('Fatima GALVEZ', 'https://olympics.com/en/at...",False,1,Spain,ES,ESP,NaN,NaN,Mixed,2020
3785,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,SILVER,"[('Alessandra PERILLI', 'https://olympics.com/...",False,2,San Marino,SM,SMR,NaN,NaN,Mixed,2020
3786,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,BRONZE,"[('Madelynn Ann BERNAU', 'https://olympics.com...",False,3,United States of America,US,USA,NaN,NaN,Mixed,2020
3787,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,NaN,"[('Zuzana STEFECEKOVA', 'https://olympics.com/...",False,4,Slovakia,SK,SVK,NaN,NaN,Mixed,2020
3788,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,NaN,"[('Yukie NAKAYAMA', 'https://olympics.com/en/a...",False,5,Japan,JP,JPN,NaN,NaN,Mixed,2020

In [8]:
summer_games_results['medal_type'] = summer_games_results['medal_type'].fillna('None')
summer_games_results['total_medals'] = summer_games_results['medal_type'].apply(lambda x: 0 if x == 'None' else 1)
summer_games_results['gold_medals'] = summer_games_results['medal_type'].apply(lambda x: 1 if x == 'GOLD' else 0)
summer_games_results['silver_medals'] = summer_games_results['medal_type'].apply(lambda x: 1 if x == 'SILVER' else 0)
summer_games_results['bronze_medals'] = summer_games_results['medal_type'].apply(lambda x: 1 if x == 'BRONZE' else 0)
summer_games_results.head()

,discipline_title,event_title,game_slug,participant_type,medal_type,athletes,rank_equal,rank_position,country_name,country_code,country_3_letter_code,value_unit,value_type,event_gender,game_year,total_medals,gold_medals,silver_medals,bronze_medals
3784,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,GOLD,"[('Fatima GALVEZ', 'https://olympics.com/en/at...",False,1,Spain,ES,ESP,NaN,NaN,Mixed,2020,1,1,0,0
3785,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,SILVER,"[('Alessandra PERILLI', 'https://olympics.com/...",False,2,San Marino,SM,SMR,NaN,NaN,Mixed,2020,1,0,1,0
3786,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,BRONZE,"[('Madelynn Ann BERNAU', 'https://olympics.com...",False,3,United States of America,US,USA,NaN,NaN,Mixed,2020,1,0,0,1
3787,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,None,"[('Zuzana STEFECEKOVA', 'https://olympics.com/...",False,4,Slovakia,SK,SVK,NaN,NaN,Mixed,2020,0,0,0,0
3788,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,None,"[('Yukie NAKAYAMA', 'https://olympics.com/en/a...",False,5,Japan,JP,JPN,NaN,NaN,Mixed,2020,0,0,0,0

In [9]:
summer_games_results['participant_type'].unique()
summer_games_results_individual = summer_games_results.loc[(summer_games_results.participant_type == 'Athlete')].copy()
summer_games_results_individual.head()

,discipline_title,event_title,game_slug,participant_type,medal_type,athletes,rank_equal,rank_position,country_name,country_code,country_3_letter_code,value_unit,value_type,event_gender,game_year,total_medals,gold_medals,silver_medals,bronze_medals
3800,Shooting,50m Rifle 3 Positions women,tokyo-2020,Athlete,None,"[('Dongqi CHEN', 'https://olympics.com/en/athl...",False,19,People's Republic of China,CN,CHN,NaN,NaN,Women,2020,0,0,0,0
3801,Shooting,50m Rifle 3 Positions women,tokyo-2020,Athlete,None,"[('Sagen MADDALENA', 'https://olympics.com/en/...",False,5,United States of America,US,USA,NaN,NaN,Women,2020,0,0,0,0
3802,Shooting,50m Rifle 3 Positions women,tokyo-2020,Athlete,None,"[('Maria MARTYNOVA', 'https://olympics.com/en/...",False,17,Belarus,BY,BLR,NaN,NaN,Women,2020,0,0,0,0
3803,Shooting,50m Rifle 3 Positions women,tokyo-2020,Athlete,BRONZE,"[('Yulia KARIMOVA', 'https://olympics.com/en/a...",False,3,ROC,ROC,ROC,NaN,NaN,Women,2020,1,0,0,1
3804,Shooting,50m Rifle 3 Positions women,tokyo-2020,Athlete,None,"[('Najmeh KHEDMATI', 'https://olympics.com/en/...",False,18,Islamic Republic of Iran,IR,IRI,NaN,NaN,Women,2020,0,0,0,0

In [10]:
# def extract_athlete_name(athletes_str):
#     if not pd.isna(athletes_str):
#         athletes_list = ast.literal_eval(athletes_str)
#         if athletes_list and isinstance(athletes_list, list):
#             return athletes_list[0][0] # Retourne le nom de l'athlète
#     return ""

# def extract_athlete_name(athletes_str):
#     if isinstance(athletes_str, str):
#         athletes_list = ast.literal_eval(athletes_str)
#         if athletes_list and isinstance(athletes_list, list):
#             return athletes_list[0][0] # Retourne le nom de l'athlète
#     return ""

def extract_athlete_name(athletes_str):
    if isinstance(athletes_str, str):
        try:
            athletes_list = ast.literal_eval(athletes_str)
            if athletes_list and isinstance(athletes_list, list):
                return athletes_list[0][0]  # Return the name of the first athlete
        except (ValueError, SyntaxError):
            return ""
    return ""

def extract_athlete_url(athletes_str):
    if isinstance(athletes_str, str):
        try:
            athletes_list = ast.literal_eval(athletes_str)
            if athletes_list and isinstance(athletes_list, list):
                return athletes_list[0][1]  # Return the name of the first athlete
        except (ValueError, SyntaxError):
            return ""
    return ""

In [11]:
summer_games_results_individual.dropna(subset=['athletes'], inplace=True)
summer_games_results_individual = summer_games_results_individual[summer_games_results_individual['athletes'].astype(bool)]

summer_games_results_individual['athlete_full_name'] = summer_games_results_individual['athletes'].apply(extract_athlete_name)
summer_games_results_individual['athlete_url'] = summer_games_results_individual['athletes'].apply(extract_athlete_url)

summer_games_results_individual.head()

,discipline_title,event_title,game_slug,participant_type,medal_type,athletes,rank_equal,rank_position,country_name,country_code,...,value_unit,value_type,event_gender,game_year,total_medals,gold_medals,silver_medals,bronze_medals,athlete_full_name,athlete_url
3800,Shooting,50m Rifle 3 Positions women,tokyo-2020,Athlete,None,"[('Dongqi CHEN', 'https://olympics.com/en/athl...",False,19,People's Republic of China,CN,...,NaN,NaN,Women,2020,0,0,0,0,Dongqi CHEN,https://olympics.com/en/athletes/dongqi-chen
3801,Shooting,50m Rifle 3 Positions women,tokyo-2020,Athlete,None,"[('Sagen MADDALENA', 'https://olympics.com/en/...",False,5,United States of America,US,...,NaN,NaN,Women,2020,0,0,0,0,Sagen MADDALENA,https://olympics.com/en/athletes/sagen-maddalena
3802,Shooting,50m Rifle 3 Positions women,tokyo-2020,Athlete,None,"[('Maria MARTYNOVA', 'https://olympics.com/en/...",False,17,Belarus,BY,...,NaN,NaN,Women,2020,0,0,0,0,Maria MARTYNOVA,https://olympics.com/en/athletes/maria-martynova
3803,Shooting,50m Rifle 3 Positions women,tokyo-2020,Athlete,BRONZE,"[('Yulia KARIMOVA', 'https://olympics.com/en/a...",False,3,ROC,ROC,...,NaN,NaN,Women,2020,1,0,0,1,Yulia KARIMOVA,https://olympics.com/en/athletes/yulia-karimova
3804,Shooting,50m Rifle 3 Positions women,tokyo-2020,Athlete,None,"[('Najmeh KHEDMATI', 'https://olympics.com/en/...",False,18,Islamic Republic of Iran,IR,...,NaN,NaN,Women,2020,0,0,0,0,Najmeh KHEDMATI,https://olympics.com/en/athletes/najmeh-khedmati

In [12]:
reduced_athletes = athletes_df[['athlete_full_name', 'athlete_year_birth', 'athlete_url']]
summer_games_results_individual = summer_games_results_individual.merge(reduced_athletes, on=['athlete_full_name', 'athlete_url'])
summer_games_results_individual.head()

,discipline_title,event_title,game_slug,participant_type,medal_type,athletes,rank_equal,rank_position,country_name,country_code,...,value_type,event_gender,game_year,total_medals,gold_medals,silver_medals,bronze_medals,athlete_full_name,athlete_url,athlete_year_birth
0,Shooting,50m Rifle 3 Positions women,tokyo-2020,Athlete,None,"[('Dongqi CHEN', 'https://olympics.com/en/athl...",False,19,People's Republic of China,CN,...,NaN,Women,2020,0,0,0,0,Dongqi CHEN,https://olympics.com/en/athletes/dongqi-chen,1988.0
1,Shooting,50m Rifle 3 Positions women,tokyo-2020,Athlete,None,"[('Sagen MADDALENA', 'https://olympics.com/en/...",False,5,United States of America,US,...,NaN,Women,2020,0,0,0,0,Sagen MADDALENA,https://olympics.com/en/athletes/sagen-maddalena,1993.0
2,Shooting,50m Rifle 3 Positions women,tokyo-2020,Athlete,None,"[('Maria MARTYNOVA', 'https://olympics.com/en/...",False,17,Belarus,BY,...,NaN,Women,2020,0,0,0,0,Maria MARTYNOVA,https://olympics.com/en/athletes/maria-martynova,1997.0
3,Shooting,10m Air Rifle women,tokyo-2020,Athlete,None,"[('Maria MARTYNOVA', 'https://olympics.com/en/...",False,24,Belarus,BY,...,NaN,Women,2020,0,0,0,0,Maria MARTYNOVA,https://olympics.com/en/athletes/maria-martynova,1997.0
4,Shooting,50m Rifle 3 Positions women,tokyo-2020,Athlete,BRONZE,"[('Yulia KARIMOVA', 'https://olympics.com/en/a...",False,3,ROC,ROC,...,NaN,Women,2020,1,0,0,1,Yulia KARIMOVA,https://olympics.com/en/athletes/yulia-karimova,1994.0

In [13]:
summer_games_results_individual = summer_games_results_individual.dropna(subset=['athlete_year_birth'])
summer_games_results_individual['athlete_year_birth'] = summer_games_results_individual['athlete_year_birth'].astype(int)
print(summer_games_results_individual['athlete_year_birth'].unique())
print(summer_games_results_individual['game_year'].unique())

[1988 1993 1997 1994 1996 1998 1987 2001 1991 1999 1995 2000 1992 1982
 2002 1980 2003 1990 1986 1985 1983 1981 1984 1976 1977 1989 1979 2004
 1970 1975 1963 1974 1978 1971 1966 1969 1972 2005 1973 1968 2007 2006
 2009 1943 2008 1964 1959 1954 1967 1965 1962 1960 1957 1955 1961 1956
 1948 1947 1958 1951 1891 1941 1938 1903 1952 1933 1950 1949 1936 1953
 1945 1937 1946 1932 1944 1942 1939 1896 1940 1935 1929 1924 1934 1895
 1931 1930 1928 1907 1922 1925 1927 1906 1920 1914 1926 1910 1915 1923
 1917 1921 1919 1913 1912 1902 1918 1908 1900 1909 1911 1916 1905 1904
 1898 1901 1892 1886 1899 1889 1893 1894 1897 1890 1884 1878 1880 1885
 1874 1883 1887 1888 1881 1864 1879 1882 1877 1872 1867 1875 1871 1873
 1865 1863 1866 1869 1868 1876 1847 1870 1862 1858 1852 1854 1859 1856
 1850 1861 1860 1857 1841 1848 1849 1840 1836 1851]
[2020 2016 2012 2008 2004 2000 1996 1992 1988 1976 1968 1984 1952 1980
 1964 1972 1960 1956 1948 1936 1928 1924 1932 1920 1908 1900 1912 1896
 1904]

In [14]:
# summer_games_results_individual['age'] = summer_games_results_individual['game_year'] - summer_games_results_individual['athlete_year_birth']
# summer_games_results_individual.tail(-20)

In [15]:
# summer_games_results_individual['age'].unique()

In [16]:
# cas bizarre
# https://olympics.com/fr/athletes/issa-abdulla-mohamed
# Première participation -> Séoul 1988
# Année de naissance -> 1995

In [17]:
# summer_games_results_individual[summer_games_results_individual['age'] == -7].head()

In [18]:
# summer_games_results_individual = summer_games_results_individual[summer_games_results_individual['age'].between(0, 50)]
# summer_games_results_individual.head()

In [19]:
summer_games_results_individual['actual_age'] = 2024 - summer_games_results_individual['athlete_year_birth']
summer_games_results_individual.head()

,discipline_title,event_title,game_slug,participant_type,medal_type,athletes,rank_equal,rank_position,country_name,country_code,...,event_gender,game_year,total_medals,gold_medals,silver_medals,bronze_medals,athlete_full_name,athlete_url,athlete_year_birth,actual_age
0,Shooting,50m Rifle 3 Positions women,tokyo-2020,Athlete,None,"[('Dongqi CHEN', 'https://olympics.com/en/athl...",False,19,People's Republic of China,CN,...,Women,2020,0,0,0,0,Dongqi CHEN,https://olympics.com/en/athletes/dongqi-chen,1988,36
1,Shooting,50m Rifle 3 Positions women,tokyo-2020,Athlete,None,"[('Sagen MADDALENA', 'https://olympics.com/en/...",False,5,United States of America,US,...,Women,2020,0,0,0,0,Sagen MADDALENA,https://olympics.com/en/athletes/sagen-maddalena,1993,31
2,Shooting,50m Rifle 3 Positions women,tokyo-2020,Athlete,None,"[('Maria MARTYNOVA', 'https://olympics.com/en/...",False,17,Belarus,BY,...,Women,2020,0,0,0,0,Maria MARTYNOVA,https://olympics.com/en/athletes/maria-martynova,1997,27
3,Shooting,10m Air Rifle women,tokyo-2020,Athlete,None,"[('Maria MARTYNOVA', 'https://olympics.com/en/...",False,24,Belarus,BY,...,Women,2020,0,0,0,0,Maria MARTYNOVA,https://olympics.com/en/athletes/maria-martynova,1997,27
4,Shooting,50m Rifle 3 Positions women,tokyo-2020,Athlete,BRONZE,"[('Yulia KARIMOVA', 'https://olympics.com/en/a...",False,3,ROC,ROC,...,Women,2020,1,0,0,1,Yulia KARIMOVA,https://olympics.com/en/athletes/yulia-karimova,1994,30

In [20]:
summer_games_results_individual[summer_games_results_individual['athlete_url'] == "https://olympics.com/en/athletes/michael-phelps-ii"]

,discipline_title,event_title,game_slug,participant_type,medal_type,athletes,rank_equal,rank_position,country_name,country_code,...,event_gender,game_year,total_medals,gold_medals,silver_medals,bronze_medals,athlete_full_name,athlete_url,athlete_year_birth,actual_age
14346,Swimming,200m individual medley men,rio-2016,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,Men,2016,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39
14347,Swimming,200m butterfly men,rio-2016,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,Men,2016,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39
14348,Swimming,100m butterfly men,rio-2016,Athlete,SILVER,"[('Michael PHELPS', 'https://olympics.com/en/a...",True,2,United States of America,US,...,Men,2016,1,0,1,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39
14349,Swimming,100m butterfly men,london-2012,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,Men,2012,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39
14350,Swimming,400m individual medley men,london-2012,Athlete,None,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,4,United States of America,US,...,Men,2012,0,0,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39
14351,Swimming,200m individual medley men,london-2012,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,Men,2012,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39
14352,Swimming,200m butterfly men,london-2012,Athlete,SILVER,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,2,United States of America,US,...,Men,2012,1,0,1,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39
14353,Swimming,200m individual medley men,beijing-2008,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,Men,2008,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39
14354,Swimming,100m butterfly men,beijing-2008,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,Men,2008,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39
14355,Swimming,200m butterfly men,beijing-2008,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,Men,2008,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39
14356,Swimming,400m individual medley men,beijing-2008,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,Men,2008,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39
14357,Swimming,200m freestyle men,beijing-2008,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,Men,2008,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39
14358,Swimming,200m butterfly men,athens-2004,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,Men,2004,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39
14359,Swimming,100m butterfly men,athens-2004,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,Men,2004,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39
14360,Swimming,400m individual medley men,athens-2004,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,Men,2004,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39
14361,Swimming,200m freestyle men,athens-2004,Athlete,BRONZE,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,3,United States of America,US,...,Men,2004,1,0,0,1,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39
14362,Swimming,200m individual medley men,athens-2004,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,Men,2004,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39
14363,Swimming,200m butterfly men,sydney-2000,Athlete,None,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,5,United States of America,US,...,Men,2000,0,0,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39

In [21]:
# medal_counts_all_time = summer_games_results_individual.groupby('athlete_full_name').agg(
#     total_medals_all_time=pd.NamedAgg(column='medal_type', aggfunc='count'),
#     gold_medals_all_time=pd.NamedAgg(column='medal_type', aggfunc=lambda x: (x == 'GOLD').sum()),
#     silver_medals_all_time=pd.NamedAgg(column='medal_type', aggfunc=lambda x: (x == 'SILVER').sum()),
#     bronze_medals_all_time=pd.NamedAgg(column='medal_type', aggfunc=lambda x: (x == 'BRONZE').sum())
# ).reset_index()

# summer_games_results_individual = summer_games_results_individual.merge(medal_counts_all_time, on='athlete_full_name', suffixes=('', '_total'))
# summer_games_results_individual

summer_games_results_individual['total_medals_all_time'] = summer_games_results_individual.groupby('athlete_url')['total_medals'].transform('sum')
summer_games_results_individual.sort_values('total_medals_all_time', ascending=False).head(20)

,discipline_title,event_title,game_slug,participant_type,medal_type,athletes,rank_equal,rank_position,country_name,country_code,...,game_year,total_medals,gold_medals,silver_medals,bronze_medals,athlete_full_name,athlete_url,athlete_year_birth,actual_age,total_medals_all_time
14352,Swimming,200m butterfly men,london-2012,Athlete,SILVER,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,2,United States of America,US,...,2012,1,0,1,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39,16
14348,Swimming,100m butterfly men,rio-2016,Athlete,SILVER,"[('Michael PHELPS', 'https://olympics.com/en/a...",True,2,United States of America,US,...,2016,1,0,1,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39,16
14362,Swimming,200m individual medley men,athens-2004,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,2004,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39,16
14361,Swimming,200m freestyle men,athens-2004,Athlete,BRONZE,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,3,United States of America,US,...,2004,1,0,0,1,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39,16
14360,Swimming,400m individual medley men,athens-2004,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,2004,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39,16
14359,Swimming,100m butterfly men,athens-2004,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,2004,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39,16
14358,Swimming,200m butterfly men,athens-2004,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,2004,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39,16
14357,Swimming,200m freestyle men,beijing-2008,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,2008,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39,16
14356,Swimming,400m individual medley men,beijing-2008,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,2008,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39,16
14355,Swimming,200m butterfly men,beijing-2008,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,2008,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39,16
14354,Swimming,100m butterfly men,beijing-2008,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,2008,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39,16
14353,Swimming,200m individual medley men,beijing-2008,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,2008,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39,16
14351,Swimming,200m individual medley men,london-2012,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,2012,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39,16
14350,Swimming,400m individual medley men,london-2012,Athlete,None,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,4,United States of America,US,...,2012,0,0,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39,16
14349,Swimming,100m butterfly men,london-2012,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,2012,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39,16
14363,Swimming,200m butterfly men,sydney-2000,Athlete,None,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,5,United States of America,US,...,2000,0,0,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39,16
14346,Swimming,200m individual medley men,rio-2016,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,2016,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39,16
14347,Swimming,200m butterfly men,rio-2016,Athlete,GOLD,"[('Michael PHELPS', 'https://olympics.com/en/a...",NaN,1,United States of America,US,...,2016,1,1,0,0,Michael PHELPS,https://olympics.com/en/athletes/michael-phelp...,1985,39,16
69063,Gymnastics Artistic,vault women,rome-1960,Athlete,BRONZE,"[('Larisa LATYNINA', 'https://olympics.com/en/...",NaN,3,Soviet Union,NaN,...,1960,1,0,0,1,Larisa LATYNINA,https://olympics.com/en/athletes/larisa-latynina,1934,90,14
69069,Gymnastics Artistic,individual all-round women,melbourne-1956,Athlete,GOLD,"[('Larisa LATYNINA', 'https://olympics.com/en/...",NaN,1,Soviet Union,NaN,...,1956,1,1,0,0,Larisa LATYNINA,https://olympics.com/en/athletes/larisa-latynina,1934,90,14

In [22]:
from sklearn.model_selection import train_test_split

df = summer_games_results_individual

train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

features = ['actual_age', 'athlete_full_name', 'country_name', 'total_medals_all_time', 'discipline_title', 'event_title']
target = 'total_medals_all_time'

In [23]:
X_train = train_df[features]
y_train = train_df[target]
X_test = test_df[features]
y_test = test_df[target]

In [24]:
numeric_features = ['actual_age', 'total_medals_all_time']
categorical_features = ['country_name', 'discipline_title', 'event_title']

In [25]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [26]:
numeric_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import classification_report

In [28]:
import warnings
warnings.filterwarnings('ignore')

In [29]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42))
])

# Train the model
model.fit(X_train, y_train)

# Evaluate the model
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.78      1.00      0.88     13649
           1       0.00      0.00      0.00      2343
           2       0.00      0.00      0.00       797
           3       0.00      0.00      0.00       329
           4       0.00      0.00      0.00       170
           5       0.00      0.00      0.00        85
           6       0.00      0.00      0.00        49
           7       0.00      0.00      0.00        13
           8       0.00      0.00      0.00        10
           9       0.00      0.00      0.00        12
          10       0.00      0.00      0.00        12
          12       0.00      0.00      0.00         5
          14       0.00      0.00      0.00         6
          16       0.00      0.00      0.00         2

    accuracy                           0.78     17482
   macro avg       0.06      0.07      0.06     17482
weighted avg       0.61      0.78      0.68     17482

In [30]:
import joblib
joblib.dump(model, './pkl/decision-tree-top-winning-athletes.pkl')

['./pkl/decision-tree-top-winning-athletes.pkl']

In [31]:
# %pip install tabulate
from tabulate import tabulate

In [32]:
X_test_df = pd.DataFrame(X_test, columns=X_test.columns)
X_test_df['True Label'] = y_test
X_test_df['Predicted Label'] = y_pred

# Afficher le tableau
# print(tabulate(X_test_df.sort_values('total_medals_all_time', ascending=False).head(20), headers='keys', tablefmt='pretty'))
print(tabulate(X_test_df.head(20), headers='keys', tablefmt='pretty'))

+-------+------------+-----------------------+--------------------------+-----------------------+---------------------+---------------------------+------------+-----------------+
|       | actual_age |   athlete_full_name   |       country_name       | total_medals_all_time |  discipline_title   |        event_title        | True Label | Predicted Label |
+-------+------------+-----------------------+--------------------------+-----------------------+---------------------+---------------------------+------------+-----------------+
| 41514 |     62     | Sandra FARMER-PATRICK |         Jamaica          |           1           |      Athletics      |    400m hurdles women     |     1      |        0        |
| 52045 |     59     |     Hans FOERSTER     |    US Virgin Islands     |           0           |      Swimming       |    200m freestyle men     |     0      |        0        |
| 58154 |     69     | Mukundahari SHRESTHA  |          Nepal           |           0           |      Athletics      |       marathon men        |     0      |        0        |
| 78225 |    108     |      Khushi RAM       |          India           |           0           | Gymnastics Artistic |         vault men         |     0      |        0        |
| 86918 |    137     |    Emil MAGNUSSON     |          Sweden          |           1           |      Athletics      |  shot put both hands men  |     1      |        0        |
| 55336 |     65     |    Maria TRUJILLO     |          Mexico          |           0           |      Athletics      |      marathon women       |     0      |        0        |
| 1837  |     33     |   Nina RADOVANOVIC    |          Serbia          |           0           |       Boxing        |   Women's Fly (48-51kg)   |     0      |        0        |
| 83242 |    114     |  George Harold KOJAC  | United States of America |           1           |      Swimming       |    100m freestyle men     |     1      |        0        |
| 12744 |     39     |   Radhouane CHEBBI    |         Tunisia          |           0           |      Wrestling      |   Freestyle 125 kg men    |     0      |        0        |
| 53408 |     69     |  Adalbert Petru KUKI  |         Romania          |           0           |       Fencing       |    foil individual men    |     0      |        0        |
| 52966 |     68     |     Myung-Woo HAN     |    Republic of Korea     |           1           |      Wrestling      |              Welterweight, Freestyle (â¤74 kilograms) Men              |     1      |        0        |
| 32610 |     44     |     Florent MAREE     |          France          |           0           | Gymnastics Artistic | individual all-round men  |     0      |        0        |
| 24901 |     43     |   Paolo BIANCHESSI    |          Italy           |           0           |        Judo         | + 100kg (heavyweight) men |     0      |        0        |
| 6069  |     44     |  Penelope LEPREVOST   |          France          |           0           | Equestrian Jumping  | Jumping Individual mixed  |     0      |        0        |
| 44177 |     67     |  Yasutoshi MORIYAMA   |          Japan           |           0           |      Wrestling      |              Light-Heavyweight, Greco-Roman (â¤90 kilograms) Men              |     0      |        0        |
| 45190 |     65     |   Pascal THIEBAULT    |          France          |           0           |      Athletics      |         5000m men         |     0      |        0        |
| 56209 |     56     | Karl-Johan GUSTAVSSON |          Sweden          |           0           |      Wrestling      |              Heavyweight, Greco-Roman (â¤100 kilograms) Men              |     0      |        0        |
| 59943 |     79     |    Gunnar JERVILL     |          Sweden          |           1           |       Archery       | individual FITA round men |     1      |        0        |
| 74198 |     96     |   Valentin MURATOV    |       Soviet Union       |           3           | Gymnastics Artistic |     pommel horse men      |     3      |        0        |
| 67210 |     90     |     Lothar MILDE      |         Germany          |           1           |      Athletics      |     discus throw men      |     1      |        0        |
+-------+------------+-----------------------+--------------------------+-----------------------+---------------------+---------------------------+------------+-----------------+

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

features = ['actual_age', 'athlete_full_name', 'country_name', 'total_medals_all_time', 'discipline_title', 'event_title']
target = 'total_medals_all_time'

numeric_features = ['actual_age', 'total_medals_all_time']
categorical_features = ['country_name', 'discipline_title', 'event_title']

numeric_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(n_estimators=100))
])

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

# chances_de_medaille = model.predict_proba(X)
# chances_de_medaille = model.predict_proba(df[features])
chances_de_medaille = model.predict_proba(df)


df['predicted_medal_prob'] = chances_de_medaille[:, 1]

top_25_athletes = df.sort_values(by=['predicted_medal_prob'], ascending=False).groupby('athlete_url')

top_25_athletes.head(10)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     13649
           1       0.99      1.00      1.00      2343
           2       0.96      0.98      0.97       797
           3       0.94      0.91      0.92       329
           4       0.86      0.78      0.82       170
           5       0.86      0.81      0.84        85
           6       0.77      0.76      0.76        49
           7       1.00      0.69      0.82        13
           8       0.82      0.90      0.86        10
           9       1.00      0.58      0.74        12
          10       0.75      1.00      0.86        12
          12       1.00      1.00      1.00         5
          14       1.00      1.00      1.00         6
          16       1.00      1.00      1.00         2

    accuracy                           0.99     17482
   macro avg       0.93      0.89      0.90     17482
weighted avg       0.99      0.99      0.99     17482

,discipline_title,event_title,game_slug,participant_type,medal_type,athletes,rank_equal,rank_position,country_name,country_code,...,total_medals,gold_medals,silver_medals,bronze_medals,athlete_full_name,athlete_url,athlete_year_birth,actual_age,total_medals_all_time,predicted_medal_prob
13036,Sailing,Laser Radial - One Person Dinghy women,beijing-2008,Athlete,None,"[('Evi VAN ACKER', 'https://olympics.com/en/at...",NaN,8,Belgium,BE,...,0,0,0,0,Evi VAN ACKER,https://olympics.com/en/athletes/evi-van-acker,1985,39,1,1.0
34554,Equestrian Jumping,individual mixed,atlanta-1996,Athlete,SILVER,"[('Wilhelm MELLIGER', 'https://olympics.com/en...",NaN,2,Switzerland,CH,...,1,0,1,0,Wilhelm MELLIGER,https://olympics.com/en/athletes/wilhelm-melliger,1953,71,1,1.0
4203,Tennis,Singles women,rio-2016,Athlete,BRONZE,"[('Petra KVITOVA', 'https://olympics.com/en/at...",NaN,3,Czech Republic,CZ,...,1,0,0,1,Petra KVITOVA,https://olympics.com/en/athletes/petra-kvitova,1990,34,1,1.0
19454,Shooting,skeet (125 targets) men,beijing-2008,Athlete,None,"[('Anders Christian GOLDING', 'https://olympic...",NaN,25,Denmark,DK,...,0,0,0,0,Anders Christian GOLDING,https://olympics.com/en/athletes/anders-christ...,1984,40,1,1.0
19453,Shooting,skeet (125 targets) men,london-2012,Athlete,SILVER,"[('Anders Christian GOLDING', 'https://olympic...",NaN,2,Denmark,DK,...,1,0,1,0,Anders Christian GOLDING,https://olympics.com/en/athletes/anders-christ...,1984,40,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48506,Swimming,400m individual medley women,barcelona-1992,Athlete,None,"[('Celine BONNET', 'https://olympics.com/en/at...",NaN,19,France,FR,...,0,0,0,0,Celine BONNET,https://olympics.com/en/athletes/celine-bonnet,1976,48,0,0.0
14079,Equestrian Eventing,individual mixed,beijing-2008,Athlete,None,"[('Marcus James TODD', 'https://olympics.com/e...",NaN,17,New Zealand,NZ,...,0,0,0,0,Marcus James TODD,https://olympics.com/en/athletes/marcus-james-...,1956,68,3,0.0
48508,Swimming,200m individual medley women,barcelona-1992,Athlete,None,"[('Jacqueline MCKENZIE', 'https://olympics.com...",NaN,15,Australia,AU,...,0,0,0,0,Jacqueline MCKENZIE,https://olympics.com/en/athletes/jacqueline-mc...,1973,51,0,0.0
19310,Shooting,50m rifle 3 positions 3x20 shots women,beijing-2008,Athlete,None,"[('Robyn VAN NUS', 'https://olympics.com/en/at...",NaN,40,Australia,AU,...,0,0,0,0,Robyn VAN NUS,https://olympics.com/en/athletes/robyn-van-nus,1982,42,0,0.0
0,Shooting,50m Rifle 3 Positions women,tokyo-2020,Athlete,None,"[('Dongqi CHEN', 'https://olympics.com/en/athl...",False,19,People's Republic of China,CN,...,0,0,0,0,Dongqi CHEN,https://olympics.com/en/athletes/dongqi-chen,1988,36,0,0.0

In [34]:
# top_25_athletes = df.sort_values(by=['total_medals_all_time'], ascending=False).head(10)
# top_25_athletes

In [35]:
# import joblib
# joblib.dump(model, './pkl/decision-tree-top-winning-athletes.pkl')